//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MyGet.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDC_PROGRESS_CHART              105
#define ID_SPEED_BAR                    106
#define IDC_SPEEDBAR                    107
#define IDS_COULD_CREATE_FOLDER         113
#define IDS_DOWNLOAD_ITEM_PROPERTY      116
#define IDS_ADD_ALTER_URL_DLG_TITLE     117
#define IDR_SCHEDULEWND                 119
#define IDR_MAINFRAME                   128
#define IDB_BLOCK_STATUS_BMP            133
#define IDD_FOLDER_SELECTION            136
#define IDB_LIST_ITEM_ICON              145
#define IDB_MAINFRAME_ENABLE            146
#define IDB_MAINFRAME_DISABLE           147
#define IDD_CATEGORY                    147
#define IDD_NEW_FOLDER                  148
#define IDB_INDEX_ITEM_ICON             149
#define IDD_OPTIONS_PROXY               149
#define IDM_CATEGORY_CONTEXT            151
#define IDM_DOWNLOAD_JOB_CONTEXT        152
#define IDM_TRAY_CONTEXT                153
#define IDD_OPTIONS_CONNECTION          154
#define IDD_OPTIONS_GENERAL             156
#define IDD_OPTIONS_PROTOCOL            157
#define IDD_OPTIONS_MONITOR             161
#define IDD_OPTIONS_GRAPH_LOG           162
#define IDD_OPTIONS_FILE_MANAGEMENT     163
#define IDD_OPTIONS_DIAL_UP             164
#define IDD_OPTIONS_SOUND               166
#define IDD_OPTIONS_OTHER               167
#define IDD_OPTIONS_SCHEDULE            173
#define IDM_COMMON_JOB_CONTEXT          178
#define IDD_ADD_BATCH_DOWNLOAD          183
#define IDB_CONTENT_ITEM_ICON           189
#define IDB_CHOICE_TYPE_BMP             201
#define IDD_SETUP_ALTERNATE_URLS        203
#define IDD_OPTIONS_MIRROR              204
#define IDD_OPTIONS_LOGIN               207
#define IDD_PROXY_SETTINGS              208
#define IDD_DOWNLOAD_PROP               209
#define IDM_VIEW_LANGUAGE_ENGLISH       224
#define IDB_OTHERS                      227
#define IDI_TRAY1                       230
#define IDI_TRAY2                       231
#define IDI_TRAY3                       232
#define IDM_CATEGORY_CONTEXT_NEW        300
#define IDM_CATEGORY_CONTEXT_PROP       301
#define IDM_CATEGORY_CONTEXT_MOVE_TO    302
#define IDM_CATEGORY_CONTEXT_DELETE     303
#define IDC_EDIT_INPUT                  1000
#define IDC_EDIT_URL                    1001
#define IDC_EDIT_PATH                   1002
#define IDC_BROWSE_FOLDER_BUTTON        1003
#define IDC_BTN_SELECT_NEW_FOLDER       1003
#define IDC_BTN_BROWSEVIRUSSCANNER      1003
#define IDC_BTN_BROWSESOUND             1003
#define IDC_CBX_CATEGORY                1004
#define IDC_EDIT_REFERER                1005
#define IDC_EDIT_RENAME                 1007
#define IDC_EDIT_COMMENT                1008
#define IDC_CHK_BROWSERFILLCOMMENTWITHCLIPBOARDCONTENT 1008
#define IDC_CHECK_LOGIN                 1009
#define IDC_EDIT_USER                   1010
#define IDC_EDIT_USERNAME               1010
#define IDC_EDT_USERNAME                1010
#define IDC_EDIT_PASSWORD               1011
#define IDC_EDT_PASSWORD                1011
#define IDC_EDIT_SPLIT                  1012
#define IDC_LIST_PROXY                  1013
#define IDC_CATEGORY_NAME_EDIT          1014
#define IDC_DEFAULT_DIR_EDIT            1015
#define IDC_CATEGORY_TREE               1017
#define IDC_CBX_HTTP_PROXY              1019
#define IDC_CBX_FTP_PROXY               1020
#define IDC_TITLE_STATIC                1036
#define IDC_DTP_DOWNLOADSTARTAT         1037
#define IDC_TEXT_URL                    1038
#define IDC_EDIT_CONNECTON_TIME_OUT     1041
#define IDC_CBX_CONNECTIONS             1041
#define IDC_EDIT_DATA_TIME_OUT          1042
#define IDC_FILELIST                    1043
#define IDC_EDIT_MAX_SIM_JOBS           1043
#define IDC_SYNCH_FOLDERS               1044
#define IDC_EDIT_NUM_OF_RETRIES         1044
#define IDC_BROWSE_TREE                 1045
#define IDC_EDIT_RETRY_DELAY            1045
#define IDC_EDT_WAITBETWEENRETRY        1045
#define IDC_BTN_NEW_FOLDER              1046
#define IDC_BTN_CREATE_NEW_CATEGORY     1046
#define IDC_TEXT_CURRENT_FOLDER         1047
#define IDC_EDT_NEW_FOLDER_NAME         1048
#define IDC_CHK_START_MAINFRAME_MINIMIZED 1055
#define IDC_CHK_PROMPT_WHEN_DROP        1056
#define IDC_CHK_STILL_DOWNLOAD_EVEN_NONRESUMABLE 1058
#define IDC_CHK_ERROR_STOP              1059
#define IDC_CHECK_PASV_MODE             1061
#define IDC_CHK_AUTO_SAVE               1062
#define IDC_EDT_AUTO_SAVE_INTERVAL      1063
#define IDC_EDIT_ASCII_MODE             1064
#define IDC_CHK_CLIPBOARDCONFIRM        1065
#define IDC_CHK_CLIPBOARDMONITOR        1066
#define IDC_EDT_MONITORTYPES            1067
#define IDC_BTN_LOGSTATE                1068
#define IDC_BTN_LOGERROR                1069
#define IDC_BTN_LOGCOMMAND              1070
#define IDC_BTN_LOGSERVER               1071
#define IDC_EDT_GRAPHSCALE              1072
#define IDC_BTN_GRAPHFORE               1073
#define IDC_BTN_GRAPHBACK               1074
#define IDC_RD_MOVEDOWNLOADEDITEM_DONOTMOVE 1076
#define IDC_RD_MOVEDOWNLOADEDITEM_PROMPT 1077
#define IDC_RD_MOVEDOWNLOADEDITEM_MOVE  1078
#define IDC_CBX_USER_AGENT              1079
#define IDC_EDIT_USER_DEFINE_AGENT      1080
#define IDC_CHK_REDIALIFDISCONNECTED    1081
#define IDC_CHK_ENABLESTOPTIMER         1082
#define IDC_CHK_HANGUPWHENDONE          1082
#define IDC_EDT_RETRYFAILEDCONNECTION   1086
#define IDC_EDIT_TITILE                 1088
#define IDC_EDT_CONNECTIONWINDOWTITLE   1088
#define IDC_LV_SOUNDS                   1091
#define IDC_BTN_PLAYSOUND               1094
#define IDC_BTN_DEFAULTMANAGER          1095
#define IDC_CHK_ENABLESOUND             1095
#define IDC_BTN_CLEARSOUND              1096
#define IDC_EDIT_EMAIL                  1097
#define IDC_CHK_GET_FILE_DATE_FROM_SERVER 1100
#define IDC_EDT_VIRUSSCANNER            1103
#define IDC_EDT_VIRUSSCANNERARGS        1105
#define IDC_CHK_STARTDOWNLOADAT_MONDAY  1110
#define IDC_CHK_STARTDOWNLOADAT_TUESDAY 1111
#define IDC_CHK_STARTDOWNLOADAT_WEDNESDAY 1112
#define IDC_CHK_STARTDOWNLOADAT_THURSDAY 1113
#define IDC_CHK_STARTDOWNLOADAT_FRIDAY  1114
#define IDC_CHK_STARTDOWNLOADAT_SATURDAY 1115
#define IDC_CHK_STARTDOWNLOADAT_SUNDAY  1116
#define IDC_DTP_DOWNLOADSTOPAT          1118
#define IDC_CHK_START_DOWNLOAD_ON_STARTUP 1120
#define IDC_SPN_GRAPHSCALE              1121
#define IDC_SPN_BLOCK_SIZE              1122
#define IDC_SPIN_CONNECTION_TIME_OUT    1122
#define IDC_SPIN_SPLIT                  1122
#define IDC_SPIN_MINSIZE                1122
#define IDC_SPN_BLOCKSIZE               1122
#define IDC_SPN_RETRYFAILEDCONNECTION   1122
#define IDC_CHK_USE_FILE_EXT            1123
#define IDC_SPIN_DATA_TIME_OUT          1123
#define IDC_SPIN_MAXHIT                 1123
#define IDC_SPN_WAITBETWEENRETRY        1123
#define IDC_CHK_FILE_SIZE_IN_BYTES      1124
#define IDC_SPIN_RETRY_DELAY            1124
#define IDC_CHK_BROWSERNETSCAPE         1124
#define IDC_SPIN_MAX_SIM_JOBS           1125
#define IDC_CHK_BROWSERIE               1125
#define IDC_SPIN_NUM_OF_RETRIES         1126
#define IDC_CHK_BROWSERCONFIRM          1126
#define IDC_CHK_BROWSERUSEALT           1127
#define IDC_RD_DESTINATIONEXISTS_OVERWRITE 1128
#define IDC_RD_DESTINATIONEXISTS_AUTORENAME 1129
#define IDC_RD_DESTINATIONEXISTS_STOP   1130
#define IDC_EDIT_SPEED_LIMIT            1131
#define IDC_RADIO_MANUAL                1132
#define IDC_RADIO_IMMEDIATELY           1133
#define IDC_RADIO_SCHEDULE              1134
#define IDC_CHECK_ALWARYS_OBEY_SPEED_LIMIT 1135
#define IDC_CHECK_ALWAYS_RETRY          1141
#define IDC_EDT_ROLL_BACK_SIZE          1147
#define IDC_CHK_LOGSETTINGBKCOLOR       1148
#define IDC_DOWNLOADED_SIZE             1151
#define IDC_CHK_VIRUSSCANDOWNLOADEDFILES 1153
#define IDC_BTN_ADD                     1155
#define IDC_BTN_ADD_PROXY               1155
#define IDC_BTN_EDIT_PROXY              1156
#define IDC_BTN_DELETE                  1157
#define IDC_EDIT_SERVER                 1159
#define IDC_EDIT_PORT                   1160
#define IDC_RIDIO_DIR_CONNECTION        1161
#define IDC_RADIO_DIR_CONNECTION        1161
#define IDC_RIDIAO_HTTP_GET             1162
#define IDC_RIDIAO_HTTP_CONNECT         1163
#define IDC_RIDIAO_FTP_USER_HOST_PORT1  1164
#define IDC_RIDIAO_FTP_USER_HOST_PORT2  1165
#define IDC_RIDIAO_FTP_OPEN_HOST        1166
#define IDC_RIDIAO_FTP_SITE_HOST        1167
#define IDC_RIDIAO_FTP_SITE_USER_HOST   1168
#define IDC_RIDIAO_SOCKS5               1169
#define IDC_TEXT_NOTICE                 1177
#define IDC_CHK_BACKUP_EVERY_DAY        1179
#define IDC_BTN_SAVE_AS_DEFAULT         1180
#define IDC_CHECK_ENABLE_COOKIE         1182
#define IDC_TEXT_RENAME                 1200
#define IDC_TEXT_COMMENT                1208
#define IDC_CHK_ALL_JOBS_USE_DEFAULT_PROXY 1210
#define IDC_CHK_DROPZONEDISPLAYGRAPH    1217
#define IDC_CHK_BROWSEROPENCANCELLEDURLS 1218
#define IDC_SUB_CATEGORY_COUNT          1225
#define IDC_TOTAL_FILES                 1226
#define IDC_COUNT_DOWNLOADED_FILES      1227
#define IDC_RD_BROWSERIEMETHOD1         1229
#define IDC_RD_BROWSERIEMETHOD2         1230
#define IDC_LIST_ALTERNATE_URLS         1231
#define IDC_BTN_SET_SUBSTITUTED_URLS    1235
#define IDC_CHK_ENABLEMIRROW            1236
#define IDC_CHK_AUTOSEARCHMIRRORSITES   1237
#define IDC_EDT_FTPSEARCHMINSIZE        1238
#define IDC_CHK_AUTOSELECTMIRROR        1239
#define IDC_EDT_FTPSEARCHMAXHIT         1240
#define IDC_CHK_AUTOCALCADDMIRRORS      1244
#define IDC_CHECK_ENABLE_MIRROR_AND_FTP_SEARCH 1249
#define IDC_CHK_MOVESOMEFILESTOPORTABLESTORAGE 1253
#define IDC_CBX_STORAGES                1254
#define IDC_CHK_LOG_FOR_EACH_DOWNLOADED_FILE 1255
#define IDC_CHECK_NO_CACHE              1256
#define IDC_CHECK_AUTH                  1257
#define IDC_EDT_BLOCKSIZE               1257
#define IDC_EDT_BLOCK_SIZE              1259
#define IDC_EDT_VIRUSSCANNERTYPES       1268
#define IDC_CHECK_STOP_AFTER_99_NO_DATA 1271
#define IDC_CHK_BROWSERIEWILDMATCH      1272
#define IDC_CHK_OPENFILEWHENDOWNLOADED  1273
#define IDC_EDT_OPENTYPES               1274
#define IDC_CHK_DOWNLOADSUCCEED         1275
#define IDC_CHK_DOWNLOADFAILED          1276
#define IDC_CHK_DOWNLOADALL             1277
#define IDC_TV_OTHERS                   1277
#define IDC_CHK_DROPZONETRANSPARENT     1281
#define IDC_BTN_BLOCKBACK               1283
#define IDB_CHECK_BOX_BMP               30996
#define IDM_JOB_START                   32773
#define IDM_JOB_PAUSE                   32774
#define IDM_JOB_DELETE                  32775
#define IDM_JOB_PROPERTIES              32776
#define IDM_JOB_OPEN_DOWNLOADED_FILE    32777
#define IDM_JOB_OPEN_DEST_DIR           32778
#define IDM_JOB_NEW_DOWNLOAD            32779
#define IDM_CATEGORY_NEW                32780
#define IDM_CATEGORY_PROP               32781
#define IDM_CATEGORY_MOVE_TO            32782
#define IDM_CATEGORY_DELETE             32783
#define IDM_TOOLS_OPTIONS               32786
#define IDM_CATEGORY_CONTEXT_OPEN       32788
#define IDM_TOOLS_DEFAULT_DOWNLOAD_PROPERTIES 32791
#define IDM_JOB_MOVE_TO                 32793
#define IDM_HELP_HOMEPAGE               32796
#define IDM_JOB_MOVE_UP                 32799
#define IDM_JOB_MOVE_DOWN               32800
#define IDM_JOB_PAUSE_ALL               32802
#define IDM_JOB_COPY_URL_TO_CLIP        32803
#define IDM_TOOLS_HANGUPWHENDONE        32804
#define IDM_TOOLS_SHUTDOWNWHENDONE      32805
#define IDM_JOB_DELETE_ALL              32807
#define IDM_JOB_SCHEDULE                32809
#define IDM_TOOLS_OBEYSPEEDLIMIT        32812
#define IDM_JOB_CHECK_FOR_UPDATE        32813
#define IDM_JOB_DOWNLOAD_AGAIN          32814
#define IDM_JOB_COMMENT                 32816
#define IDM_EDIT_FINDNEXT               32817
#define IDM_JOB_ADD_BATCH_DOWNLOAD      32819
#define IDM_JOB_VIRUS_SCAN              32820
#define IDM_JOB_RENAME_RENAME           32822
#define IDM_TOOLS_CONNECTDISCONNECT     32848
#define IDM_JOB_START_ALL               32849
#define IDM_JOB_BROWSE_REFERRER         32850
#define IDM_JOB_EXPORT                  32857
#define IDM_TOOLS_SITEEXLORER           32866
#define ID_BUTTON32869                  32869
#define ID_BUTTON32870                  32870
#define ID_BUTTON32871                  32871
#define ID_BUTTON32872                  32872
#define ID_BUTTON32873                  32873
#define ID_BUTTON32874                  32874
#define ID_BUTTON32875                  32875
#define ID_BUTTON32876                  32876
#define ID_BUTTON32877                  32877
#define ID_BUTTON32878                  32878
#define ID_BUTTON32879                  32879
#define ID_BUTTON32880                  32880
#define ID_BUTTON32881                  32881
#define ID_BUTTON32882                  32882
#define ID_BUTTON32883                  32883
#define ID_BUTTON32884                  32884
#define ID_BUTTON32885                  32885
#define ID_BUTTON32886                  32886
#define ID_BUTTON32887                  32887
#define ID_BUTTON32888                  32888
#define IDM_JOB_RENAME_COMMENT_AS_FILENAME 32888
#define IDM_FILE_MERGE_DB               32889
#define IDM_FILE_OPEN                   57601
#define ID_FILE_SAVEAS                  57604
#define IDM_EDIT_FIND                   57636
#define IDM_HELP_ABOUT                  57664
#define ID_FILE_EXIT                    57665
#define IDS_NEW_CATEGORY_TITLE          61222
#define IDS_CANNOT_MOVE_DELETE_CATEGORY 61224
#define IDS_DELETE_CATEGORY_PROMPT      61225
#define IDS_OPTION_TITLE                61227
#define IDS_NEW_DOWNLOAD_TILE           61229
#define IDS_PROP_TITLE                  61230
#define IDS_NEW_CATEGORY_DESC           61232
#define IDS_MOVE_CATEGORY_TITLE         61233
#define IDS_MOVE_CATEGORY_DESC          61234
#define IDS_DEFAULT_DOWNLOAD_PROPERTY_TITLE 61236

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32894
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           120
#endif
#endif
